### PR TITLE
Add support for Redhat, other Debian based distros... Use archive type instead of wget, change proxy_host and proxy_port to proxy_uri

### PR DESCRIPTION
**Pull request by farlerac**

### CODE REVIEW

**Comment by helenes-r7** [comment]
Hi @farlerac ,

Thanks for helping us expand our Nexpose module to include RHEL/CentOS support. We currently don't have automated testing, so I'll take some time this week to manually test and merge this request.

**Comment by edestecd** [comment]
Do you have any plans to publish this to the puppet forge?

**Comment by helenes-r7** [comment]
Definitely do, once we clean up the code a bit and add automated testing.

**Comment by edestecd** [comment]
OK. We have some issues on our Fork that we are working on. You should see them soon.

**Comment by edestecd** [comment]
https://github.com/MiamiOH/puppet-nexpose/issues

**Comment by edestecd** [comment]
Could you turn on issues in this repo?  OR do you use an external issue tracker?

**Comment by helenes-r7** [comment]
We don't have an external issue tracker, so I'll look into turning on issues in this repo. Thanks!

**Comment by helenes-r7** [comment]
Hey @farlerac and @edestecd,

Quick update: We're currently working on setting up testing for this module and will be merging this pull request soon. I enabled issues (thanks for the request) so please feel free :)

**Comment by helenes-r7** [comment]
Thank you @farlerac and @edestecd for your contributions!

**Pull request merged**
